### ISSUE TITLE
build error for VS2019, libeay32 (dll)

### ISSUE THREAD

**Issue by waltje** [kiyolee/openssl1_0-win-build#2]
Hi:

Building libeay32-static runs fine.  So, perl and nasm are found, and work.

However, building the shared version does not..:

`Build started...
1>------ Build started: Project: libeay32, Configuration: Release Win32 ------
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>Performing Custom Build Tools
1>File ssl/tls1.h: cannot parse: ()
1>
1>#INFO::;
1>File ssl/tls1.h: cannot parse: ()
1>
1>#INFO::;
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for '..\..\crypto\aes\asm\aes-586.pl;..\..\crypto\aes\asm\aesni-x86.pl;..\..\crypto\aes\asm\vpaes-x86.pl;..\..\crypto\bf\asm\bf-586.pl;..\..\crypto\bn\asm\bn-586.pl;..\..\crypto\bn\asm\co-586.pl;..\..\crypto\bn\asm\x86-gf2m.pl;..\..\crypto\bn\asm\x86-mont.pl;..\..\crypto\camellia\asm\cmll-x86.pl;..\..\crypto\cast\asm\cast-586.pl;..\..\crypto\des\asm\crypt586.pl;..\..\crypto\des\asm\des-586.pl;..\..\crypto\md5\asm\md5-586.pl;..\..\crypto\modes\asm\ghash-x86.pl;..\..\crypto\rc4\asm\rc4-586.pl;..\..\crypto\ripemd\asm\rmd-586.pl;..\..\crypto\sha\asm\sha1-586.pl;..\..\crypto\sha\asm\sha256-586.pl;..\..\crypto\sha\asm\sha512-586.pl;..\..\crypto\whrlpool\asm\wp-mmx.pl;..\..\crypto\x86cpuid.pl;..\..\util\mkdef.pl' exited with code 1.
1>Done building project "libeay32.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========`

After that second #INFO::: line, it just hangs until i manually kill perl.exe.  Cancelling the build does not work, hence the killing.

I am using perl version 5.36, as shown:

`perl -v

This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-msys-thread-multi

Copyright 1987-2022, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on this system using "man perl" or "perldoc perl".  If you have access to the Internet, point your browser at https://www.perl.org/, the Perl Home Page.`

as supplied with the Git for Windows package.

Did this come up earlier?

--fred

**Comment by waltje** [comment]
Errr.. apology for the formatting, <> did not work as expected..

**Comment by kiyolee** [comment]
Are you building the whole solution? Or you just open the vcxproj file and build just the dll?

**Comment by waltje** [comment]
The whole thing.

However... just to make sure, I installed Strawberry Perl, and whaddayaknow...

So... strawberries it is, from here on!

You can close this, but may want to update the docs to stress that MinGW/MSYS2/Git perl will NOT work,
for whatever reason.

**Comment by kiyolee** [comment]
MSYS2 is its own ecosystem and doesn't necessarily play nice with native Windows environment.
Native Windows Perl installation like Strawberries is indeed required.
I'd guess that MSYS2 just can't handle proper Windows path. In MSYS2, things are expected to be more like posix.
